# Generated by Django 4.1.6 on 2023-02-23 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0, max_digits=8), max_digits=8),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 19, 34, 23, 331449)),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
