# Generated by Django 4.1.6 on 2023-02-23 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 19, 40, 30, 978121)),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
