# Generated by Django 4.1.6 on 2023-02-23 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 20, 7, 31, 289335)),
        ),
    ]
