# Generated by Django 4.1.6 on 2023-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
